using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace CodingFlow.OptionsBindingsGenerator
{
    internal static class OutputGenerator
    {
        public static (string source, string className) GenerateOutput(ImmutableArray<INamedTypeSymbol> types)
        {
            var namespaceId = types.First().ContainingAssembly.Name;
            var formattedOptions = CreateFormattedOptions(types);
            var formattedValidators = CreateFormattedValidators(types);

            var source =
$@"// <auto-generated/>
#nullable restore

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace CodingFlow.Generated.{namespaceId};

internal static class OptionsBindings
{{
    public static IServiceCollection AddOptionsBindings(this IServiceCollection services, IConfigurationManager configuration)
    {{
{string.Join(@"
", formattedOptions)}

{string.Join(@"
", formattedValidators)}

        return services;
    }}
}}
";

            return (source, "OptionsBindings");
        }

        private static IEnumerable<string> CreateFormattedOptions(ImmutableArray<INamedTypeSymbol> types)
        {
            var formattedOptions = types.Select(type =>
            {
                var optionsAttribute = type.GetAttributes().First(attribute => attribute.AttributeClass.Name == nameof(OptionsBindingsAttribute));
                var constructorArguments = optionsAttribute.ConstructorArguments;
                var isValidateOnStart = constructorArguments.First(argument => argument.Type.SpecialType == SpecialType.System_Boolean).Value as bool?;
                var FormattedAddOptionsMethod = isValidateOnStart == true
                    ? "AddOptionsWithValidateOnStart"
                    : "AddOptions";
                var formattedTypeName = type.ToDisplayString();
                var sectionName = constructorArguments.First(argument => argument.Type.SpecialType == SpecialType.System_String).Value as string;
                var isRoot = string.IsNullOrEmpty(sectionName);
                var formattedBindValue = isRoot
                    ? "configuration"
                    : $@"configuration.GetSection(""{sectionName}"")";


                return $@"        services.{FormattedAddOptionsMethod}<{formattedTypeName}>().Bind({formattedBindValue});";
            });

            return formattedOptions;
        }

        private static IEnumerable<string> CreateFormattedValidators(ImmutableArray<INamedTypeSymbol> types)
        {
            var formattedValidators = types.Select(type =>
            {
                var formattedTypeName = type.ToDisplayString();
                var validatorName = $"Validate{type.Name}";
                var validatorNamespace = type.ContainingNamespace;
                var formattedValidatorName = $"{validatorNamespace}.{validatorName}";

                return $@"        services.AddSingleton<IValidateOptions<{formattedTypeName}>, {formattedValidatorName}>();";
            });

            return formattedValidators;
        }
    }
}