// <auto-generated/>
#nullable restore

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace CodingFlow.Generated.OptionsBindingsGenerator.GeneratedTestProject;

internal static class OptionsBindings
{
    public static IServiceCollection AddOptionsBindings(this IServiceCollection services, IConfigurationManager configuration)
    {
        services.AddOptions<TestLibrary.NatsServiceOptions>().Bind(configuration.GetSection("Services:Nats"));
        services.AddOptionsWithValidateOnStart<TestLibrary.ServiceStreamConsumerOptions>().Bind(configuration);

        services.AddSingleton<IValidateOptions<TestLibrary.NatsServiceOptions>, TestLibrary.ValidateNatsServiceOptions>();
        services.AddSingleton<IValidateOptions<TestLibrary.ServiceStreamConsumerOptions>, TestLibrary.ValidateServiceStreamConsumerOptions>();

        return services;
    }
}
